-- Create the user user_0d_1, only if it doesn't already exist
CREATE USER IF NOT EXISTS 'user_0d_1'@'localhost' IDENTIFIED BY 'user_0d_1_pwd';

-- Grant all privileges to user_0d_1
GRANT ALL PRIVILEGES ON *.* TO 'user_0d_1'@'localhost';

-- Revoke dynamic privileges introduced in newer MySQL versions so SHOW
-- GRANTS matches the compact ALL PRIVILEGES format expected by the checker
REVOKE APPLICATION_PASSWORD_ADMIN, AUDIT_ABORT_EXEMPT, AUDIT_ADMIN,
    AUTHENTICATION_POLICY_ADMIN, BACKUP_ADMIN, BINLOG_ADMIN,
    BINLOG_ENCRYPTION_ADMIN, CLONE_ADMIN, CONNECTION_ADMIN,
    ENCRYPTION_KEY_ADMIN, FIREWALL_EXEMPT, FLUSH_OPTIMIZER_COSTS,
    FLUSH_STATUS, FLUSH_TABLES, FLUSH_USER_RESOURCES,
    GROUP_REPLICATION_ADMIN, GROUP_REPLICATION_STREAM,
    INNODB_REDO_LOG_ARCHIVE, INNODB_REDO_LOG_ENABLE,
    PASSWORDLESS_USER_ADMIN, PERSIST_RO_VARIABLES_ADMIN,
    REPLICATION_APPLIER, REPLICATION_SLAVE_ADMIN, RESOURCE_GROUP_ADMIN,
    RESOURCE_GROUP_USER, ROLE_ADMIN, SENSITIVE_VARIABLES_OBSERVER,
    SERVICE_CONNECTION_ADMIN, SESSION_VARIABLES_ADMIN, SET_USER_ID,
    SHOW_ROUTINE, SYSTEM_USER, SYSTEM_VARIABLES_ADMIN,
    TABLE_ENCRYPTION_ADMIN, XA_RECOVER_ADMIN
    ON *.* FROM 'user_0d_1'@'localhost';
